@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtaXhlZGhlZGdlaG9nMjc5IiwiaWQiOiIxYTRkMDBhNi02M2ZlLTQ3ZmItYTNmNy0xOTBkMTExNmFiYzAiLCJyb2xlIjoiUEFSVElDSVBBTlQiLCJpYXQiOjE2NTE2Nzg5MzEsImV4cCI6MTY1MTY4MDEzMX0.sYJIejG8eInVNpliEVPS7FwLfX6pN8dbyDBjHlFjmMY
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtaXhlZGhlZGdlaG9nMjc5IiwiaWQiOiIxYTRkMDBhNi02M2ZlLTQ3ZmItYTNmNy0xOTBkMTExNmFiYzAiLCJyb2xlIjoiUEFSVElDSVBBTlQiLCJpYXQiOjE2NTE2Nzg5MzEsImV4cCI6MTY1MjI4MzczMX0.oH8WZAkZ9wUieQJqy-HCet9Z6E-MLDH3y-MdW-YOqfQ

GET {{host}}/

###

POST {{host}}/login
content-type: application/json

{
    "username" : "mixedhedgehog279",
    "password" : "jifipakafa"
}

###

POST {{host}}/auth/refreshToken
content-type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}

###


POST {{host}}/logout
Authorization: Bearer {{refreshToken}}

###
GET {{host}}/feed
content-type: application/json
Authorization: Bearer {{accessToken}}

### 
POST {{host}}/event
content-type : application/json
Authorization: Bearer {{accessToken}}

{
    "postId" : "0615cfea-b4dd-475b-a315-630fb9c1e152",
    "name" : "REACTION",
    "value" : "DISGUST"
}

###

POST {{host}}/study-phase
content-type : application/json
Authorization: Bearer {{accessToken}}