@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjb21wZXRlbnRtYW5kcmlsbDQ4MSIsImlkIjoiMDA2MTVlNTgtMWI1My00Mjk3LWFlNGUtZDE5NzE3YjBlODhlIiwicm9sZSI6IlBBUlRJQ0lQQU5UIiwiaWF0IjoxNjUyMjYwNjQxLCJleHAiOjE2NTIyNjE4NDF9.9sDMIZMRYrDG9fb2iMhxrTmF7fSl2ODBbi5SUnlPcA4
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjb21wZXRlbnRtYW5kcmlsbDQ4MSIsImlkIjoiMDA2MTVlNTgtMWI1My00Mjk3LWFlNGUtZDE5NzE3YjBlODhlIiwicm9sZSI6IlBBUlRJQ0lQQU5UIiwiaWF0IjoxNjUyMjYwNjQxLCJleHAiOjE2NTI4NjU0NDF9.1Er12BIgl1LHZzZx524KDl0aKrezwc8HiOnA0r5Bf-k

GET {{host}}/

###

POST {{host}}/login
content-type: application/json

{
    "username" : "competentmandrill481",
    "password" : "zaqetuguwa"
}

###

POST {{host}}/auth/refreshToken
content-type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}

###


POST {{host}}/logout
Authorization: Bearer {{refreshToken}}

###
GET {{host}}/feed
content-type: application/json
Authorization: Bearer {{accessToken}}

### 
POST {{host}}/event
content-type : application/json
Authorization: Bearer {{accessToken}}

{
    "postId" : "0615cfea-b4dd-475b-a315-630fb9c1e152",
    "name" : "REACTION",
    "value" : "DISGUST"
}

###

POST {{host}}/study-phase
content-type : application/json
Authorization: Bearer {{accessToken}}


###

POST {{host}}/share
content-type : application/json
Authorization: Bearer {{accessToken}}

{
    "postId" : "c30c6d52-b32f-4e4a-af18-9b63b14926c9",
    "action" : "SHARE"
}