name: Deploy Production
on:
  push: 
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      psych-study-platform: ${{ steps.filter.outputs.psych-study-platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            psych-study-platform:
                - 'psych-study-platform/backend/**/*'
                - 'psych-study-platform/frontend/**/*'

  psych-study-platform:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.psych-study-platform == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          cd psych-study-platform/frontend
          echo "installing dependencies"
          npm install --force
          echo "building frontend"
          npm run build:production

          
      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/psych-study-platform
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: psych-study-platform/backend/

      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
          command: set image --record deployment/psych-study-platform-production psych-study-platform-production=tattletech/psych-study-platform:${{ steps.vars.outputs.sha_short }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/psych-study-platform-production

