name: Send Study Reminder Emails
on: workflow_dispatch

env:
  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
  DB_HOST: ${{ secrets.DB_HOST}}
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  SERVICE_AWS_ACCESS_KEY_ID: ${{secrets.SERVICE_AWS_ACCESS_KEY_ID}}
  SERVICE_AWS_SECRET_ACCESS_KEY: ${{secrets.SERVICE_AWS_SECRET_ACCESS_KEY}}
  NODE_ENV: production

jobs:
  send-email:
    runs-on: ubuntu-latest
    name: "Send Reminder Emails"
    environment:
      name: production
      url: https://docs.google.com/spreadsheets/d/14RYZt4UofeRyascpsyjagnxYQ3kbgJMB9B5vayE5H9Y/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send out Emails
        uses: ./actions/post-status-breakdown
        with:
          mode: "SEND_STUDY_EMAIL"
